import Image from "next/image";
import wsuMap from "@/assets/img/wsu-map.png";
import { HowItWorks } from "@/components/how-it-works";
import { SiteHeader } from "@/components/site-header";

export default function Home() {
	return (
		<>
			<SiteHeader />

			<main className="flex flex-1 flex-col">
				<section id="hero" className="relative flex min-h-svh flex-col overflow-hidden">
					{/* Map generated by https://terraink.app/ */}
					<Image
						className="absolute inset-0 size-full object-cover"
						src={wsuMap}
						alt="Map of Wayne State University campus"
						priority
					/>

					<div className="relative mx-auto flex w-full max-w-7xl flex-1 flex-col justify-end px-5 pt-48 pb-10 sm:px-8 lg:justify-center lg:pb-20">
						<div className="max-w-xl border border-border bg-background p-6 sm:p-10">
							<h1 className="text-display">
								Your next problem set is somewhere on campus.
							</h1>

							<p className="mt-6 max-w-prose text-body-lg text-muted-foreground">
								Voluptate veniam fugiat veniam pariatur adipisicing. Commodo in et
								aliquip. Nisi ea sit culpa duis exercitation do sit ullamco
								excepteur eiusmod magna laborum cupidatat minim do.
							</p>
						</div>
					</div>
				</section>

				<HowItWorks />
			</main>
		</>
	);
}
