CREATE TABLE "public"."challenges" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "challenge_name" text,
  "class"          text,
  "time"           integer,
  CONSTRAINT "challenges_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."challenges"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."location" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "challenge"     double precision,
  "reveal_status" boolean,
  "location_info" double precision,
  CONSTRAINT "location_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."location"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "id"        uuid NOT NULL,
  "lastname"  text NOT NULL,
  "firstname" text NOT NULL,
  "role"      text NOT NULL,
  CONSTRAINT "check_role" CHECK ((role = ANY (ARRAY['student'::text, 'professor'::text]))),
  CONSTRAINT "profiles_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."submissions" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "student"    text,
  "score"      smallint,
  "chellenge"  text,
  CONSTRAINT "submissions_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."submissions"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id);

CREATE POLICY "policyforrole" ON "public"."profiles"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = id));

COMMENT ON TABLE "public"."challenges" IS 'the table that stores all information related to the challenges';

COMMENT ON TABLE "public"."location" IS 'the information table with the location of each challenge';

COMMENT ON TABLE "public"."submissions" IS 'the table to store information on the work submitted by each student';

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."challenges" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."location" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."submissions" TO "anon", "authenticated", "postgres", "service_role";

